test:test.cpp
	g++ -std=c++11 $^ -o $@ -lz -lpthread -lboost_filesystem -lboost_system
test2:test2.cpp
	g++ -std=c++11 $^ -o $@ -lz -lpthread -lboost_filesystem -lboost_system
main:main.cpp
	g++ -std=c++11 $^ -o $@ -lz -lpthread -lboost_filesystem -lboost_system
